/*========================================================================================================================
* @author: Kalash 
* @date: 13/08/2021
* @description: This test classes reference to CP_CheckRecursive
==========================================================================================================================*/
@isTest
public class CP_CheckRecursiveTest {
    @istest
    static void runOnceTest(){
        CP_CheckRecursive.runOnce();
    }

}